### ISSUE TITLE
Problème véhicule

### ISSUE THREAD

**Issue by TheGeekGamer91** [indilo53/fivem-esx_garage#1]
Bonjour. Alors déjà merci pour ce super script. Ensuite, est-ce normal que l'on puisse mettre n'importe quel véhicule dans le garage ? On peut voler un véhicule et le mettre dedans et le garder.

**Comment by indilo53** [comment]
Oui c'est normal mais on pourra savoir dans le script police si oui ou non le vehicule est volé. Ce n'est pas encore implémenté.

**Comment by TheGeekGamer91** [comment]
D'accord. Merci. Bonne continuation :D
