### ISSUE TITLE
Néons manquant?

### ISSUE THREAD

**Issue by ig0ne** [indilo53/fivem-esx_garage#2]
Salut, déjà un grand merci à toi pour tous les scripts!
Quand je rentre un véhicule modifié au ls custom dans le garage je peux le ressortir avec toutes les modifs sauf les néons.
Je pense qu'il doit manquer "neonlayout" ou "neonkit"  pour pouvoir sauvegarder les néons dans la Bdd car tu n'as que le "neoncolor".

**Comment by indilo53** [comment]
Merci, je vais voir ca

**Comment by TonTonSheitan** [comment]
yo all :) 

Moi le petit souci avec le garage c'est que mais véhicule sont dans la DB mais il ne sont plus dans mon garage, et tout les joueur c'est pareil, je te fais juste un retour c'est pas trés grave pour le moment :) 

Merci

**Comment by indilo53** [comment]
Essaie de vider le cache et de redémarrer le serveur je viens de tester ca fonctionne

**Comment by TonTonSheitan** [comment]
oui oui il et vider tout les 4 heures pendant notre reboot je vais voir au  reboot de 18 heure si j'ai toujours ce petit problème ;)

**Comment by Lariime** [comment]
TonTonSheitan moi j'ai aucuns souci, tu doit avoir loupé un truc ou mal importé le .sql :)

**Comment by TonTonSheitan** [comment]
cebon je n'ai plus aucun soucy depuis, sa mais arrivée que 1 fois je sais pas pourquoi, c'est un mystère ;)
